### ISSUE TITLE
Backpack Modals does not close

### ISSUE THREAD

**Issue by NimaSoroush** [Skyscanner/backpack#252] opened 2017-11-08 10:49 UTC
**Context:**
Backpack modal does not close by single click on outside modal's box. This is intermittent

**Repro steps:**
- go to http://backpack.prod.aws.skyscnr.com/components/web/modals/
- Open modal
- Quickly click outside of modal box

_Note: Reproduced in chrome and firefox_

**Comment by georgegillams** [comment] 2017-12-08 09:01
Hi @NimaSoroush  - thanks for reporting this!
This may be due to the app thinking you are dragging rather than clicking, which sometimes happens with high-precision input devices such as Wacom Bamboos. Would you mind telling us what pointing device you are using?
If this is what's happening then maybe we should update our check to discount a "drag" action if it is over a short enough distance. Will have a think 😸

**Comment by NimaSoroush** [comment] 2017-12-08 09:33
Hi @georgegillams 
I can actually reproduce it on my Mac machine with chrome and firefox. I am definitely not dragging. I just quickly click outside of modal box. If I do it slowly the modal will close. My though is that some kind of asynchronous initialization happening which causes this.

**Comment by georgegillams** [comment] 2017-12-08 09:54
Hmm.. I don't seem to be able to reproduce this in either browser on macOS. I've tried using Auto Mouse Click to perform the click in 1ms, and it works fine.

Do you mind providing more details about your system?

**Comment by georgegillams** [comment] 2017-12-08 09:56
Also just to let you know our documentation has moved to https://backpack.github.io/components/web/modals/ (I although I tested this on the link you provided to the old docs
)

**Comment by NimaSoroush** [comment] 2017-12-08 13:56
@georgegillams : Here is the video of reproducing it
https://screencast.com/t/c3tdsimsKgI

and system detail:
![2017-12-08_1353](https://user-images.githubusercontent.com/7963223/33768837-9a41565c-dc1f-11e7-8584-a5bead6cf487.png)

**Comment by georgegillams** [comment] 2018-02-16 09:51
Hey @NimaSoroush  - I think we may have now fixed this issue (although we haven't yet released the changes). You can test the change here https://backpack.github.io/components/web/modals/ and https://backpack.github.io/components/web/dialogs/

Please let us know if you don't think we have resolved your issue.

We'll give you a heads-up when we actually release this change so that you can update your NPM dependency and get the fix!
Thanks again for raising this!

**Closed** 2018-02-16 10:45 UTC
Labels: bug
